CREATE TABLE IF NOT EXISTS "public"."group_icons" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "url" "text" DEFAULT ''::"text" NOT NULL
);

ALTER TABLE "public"."group_icons" OWNER TO "postgres";

COMMENT ON TABLE "public"."group_icons" IS 'グループ用画像';

ALTER TABLE "public"."group_icons" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."group_icons_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
